### PR TITLE
Fix for #400 - Whitespaces and Version Constraints

### LINKED ISSUE #402: We are facing the issue with the latest version(v1.1.0) of tfswitcher
Our pipeline was running fine with v1.0.2, but suddenly in one step our pipeline download the latest tfswitcher(v1.1.0) and then pipeline got failed. We are facing the below error :

FATAL Error parsing configuration file: "exact constraint (\"= 1.1.9, = 1.1.9\") cannot be combined with other conditions"

### PR DESCRIPTION
**Pull request by MatrixCrawler**
- added fix for #400 when the comparator is not separated from the version number by a space
- possibly fixes #402 as well

### CODE REVIEW

File: lib/param_parsing/versiontf.go [hunk 1]
```diff
@@ -77,3 +78,9 @@ func isTerraformModule(params Params) bool {
 	module, err := tfconfig.LoadModule(params.ChDirPath)
 	return err == nil && len(module.RequiredCore) > 0
 }
+
+func cleanupVersionConstraints(constraint string) string {
+	regex := regexp.MustCompile(`(?P<Comparator>\D+)(?P<Version>(\d+\.\d+\.\d+)(-[a-zA-z]+\d*)?)$`)
```
Comment (yermulnik) [inline lib/param_parsing/versiontf.go:72]: @MatrixCrawler First of all thanks for taking care of it — I indeed missed "improperly" formatted version constraints where constraint operator isn't separated from the version =(
My point is looking up `(\d+\.\d+\.\d+)` is incorrect since version can be specified as `major`, `major.minor`, and `major.minor.patch` (with an optional suffix that should fall under semver though). Hence we probably should better look up constraint operators instead: https://developer.hashicorp.com/terraform/language/expressions/version-constraints#version-constraint-syntax — `=`, `!=`, `>`, `>=`, `<`, `<=`, `~>`. And ideally follow what TF Config Inspect does: https://github.com/hashicorp/terraform-config-inspect/blob/master/tfconfig/load_hcl.go#L71-L78 (didn't go deeper though)

Comment (MatrixCrawler) [reply lib/param_parsing/versiontf.go:72]: I use the hashicorp version constraint checker now. no need for manually checking.

Comment (yermulnik) [reply lib/param_parsing/versiontf.go:72]: Ah, just saw the ce0909ec0b8abb0d5478a944e1eabd1e23e7fcdc 👍🏻

File: lib/param_parsing/versiontf.go [hunk 2]
```diff
@@ -12,7 +12,7 @@ import (
 
 func GetVersionFromVersionsTF(params Params) (Params, error) {
 	var tfConstraints []string
-	var exactConstraints []string
+	//var exactConstraints []string
```
Comment (yermulnik) [inline lib/param_parsing/versiontf.go:15]: We probably can drop this as it is not used anymore

**Review by yermulnik — APPROVED** [review]

File: lib/param_parsing/versiontf.go (hunk 2 above)
Comment (MatrixCrawler) [reply lib/param_parsing/versiontf.go]: Thanks for finding. Deleted.
