### PR TITLE
fix: Commad-line flags to show/install latest stable versions are broken

### LINKED ISSUE #585: Commad-line flags to show/install latest stable versions are broken
```bash
> tfswitch --version
Version: v1.4.5

> tfswitch --help
[…]
 -s, --latest-stable=value
                    Latest implicit version based on a constraint. Ex: tfswitch
                    --latest-stable 0.13.0 downloads 0.13.7 and 0.13 downloads
                    0.15.5 (latest)
 -S, --show-latest-stable=value
                    Show latest implicit version. Ex: tfswitch
                    --show-latest-stable 0.13 prints 0.13.7 (latest)
[…]

> tfswitch 1.10.5
01:37:29.351 INFO Reading configuration from "/home/georgii/.tfswitch.toml"
01:37:29.353 INFO Switched Terraform to version "1.10.5"

> tfswitch -s 1.9
01:38:57.361 INFO Reading configuration from "/home/georgii/.tfswitch.toml"
01:38:57.464 INFO Matched version: "1.12.1"
01:38:57.464 INFO Switched Terraform to version "1.12.1"

> tfswitch -S 1.9
01:39:26.223 INFO Reading configuration from "/home/georgii/.tfswitch.toml"
01:39:26.311 INFO Matched version: "1.12.1"
1.12.1
```

### PR DESCRIPTION
**Pull request by yermulnik**
Resolves #585

### CODE REVIEW

File: lib/list_versions.go [hunk 1]
```diff
@@ -183,34 +190,35 @@ func removeDuplicateVersions(elements []string) []string {
...
+	var verType string
+	var semverRegex *regexp.Regexp
+
+	switch len(reqType) {
+	case 0:
+		verType = "full"
+	case 1:
+		verType = reqType[0]
+	default:
+		logger.Fatalf("Internal error: invalid number of arguments (must be 2, got %d)", 1+len(reqType))
```
[the remark this answers is not in the document]
Comment (yermulnik) [reply lib/list_versions.go]: > The fatal error message for `validVersionFormat` claims “must be 2” arguments, but the function actually accepts 0 or 1 optional `reqType` parameters.

Isn't true.

File: lib/list_versions.go [hunk 2]
```diff
@@ -14,15 +14,22 @@ type tfVersionList struct {
...
-		// Getting versions from body; should return match /X.X.X-@/ where X is a number,@ is a word character between a-z or A-Z
-		semver = `\/?(\d+\.\d+\.\d+)(-[a-zA-z]+\d*)?/?"`
+		semver = `\/?` + regexSemVer["full"] + `/?"`
 	} else if !preRelease {
-		// Getting versions from body; should return match /X.X.X/ where X is a number
-		// without the ending '"' pre-release folders would be tried and break.
-		semver = `\/?(\d+\.\d+\.\d+)\/?"`
+		semver = `\/?` + regexSemVer["patch"] + `\/?"`
 	}
 	r, err := regexp.Compile(semver)
```
[the remark this answers is not in the document]
Comment (yermulnik) [reply lib/list_versions.go:39]: Good catch. Though this would require larger re-factoring of this lib and I'd prefer to do it sometime later 🤷🏻

File: lib/list_versions.go [hunk 3]
```diff
@@ -14,15 +14,22 @@ type tfVersionList struct {
 	tflist []string
 }
 
+// Semantic version regexes without `^` and `$` anchors
+// Follows https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
+var regexSemVer = map[string]string{
```
Comment (MatthewJohn) [inline lib/list_versions.go]: I do love a good complex regex... and this wall of text is satisfies that

Comment (MatthewJohn) [reply lib/list_versions.go]: On another note, because this is just a map, it doesn't allow for any static checking.
e.g.:
```
var regexSemVer = map[string]string{
	"blahy": "yes",
}

func main() {
	println(regexSemVer["blahay"])
}

```
Runs fine and just outputs an empty string, which isn't great.

I'd suggest doing:
```
var regexSemVer = struct {
	Full             string
	Minor            string
	Patch            string
	PreReleaseSuffix string
}{
	Full:             `(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?`,
	Minor:            `(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)`,
	Patch:            `(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)`,
	PreReleaseSuffix: `\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?`,
}
```

The functions that pass what type of validation they want to do can still pass this.

e.g.:
```
func validVersionFormat(version string, validation ...string) bool {
	var validationString string
	var semverRegex *regexp.Regexp

	switch len(validation) {
	case 0:
		validationString = regexSemVer.Full
	case 1:
		validationString = validation[0]
	default:
		logger.Fatalf("Internal error: invalid number of arguments (must be 2, got %d)", 1+len(validation))
	}

	regexp.MustCompile(`^` + validationString + `$`)

	return semverRegex.MatchString(version)
}
```
This makes the logic of this function easier and more bullet-proof.
Also calling it isn't less verbose:
```
validVersionFormat(version, regexSemVer.Patch)
```

Hope it doesn't seem knit-picky, I'd just be conserned that a typo in the map indexing could easily go uncaught and that function becomes more verbose (as it needs to handle each index of the map for validation and there's some duplication as well, which is tidied up

Comment (MatthewJohn) [reply lib/list_versions.go]: Could even just pre-compile into the struct:
```
var regexSemVer = struct {
	Full             *regexp.Regexp
	Minor            *regexp.Regexp
	Patch            *regexp.Regexp
	PreReleaseSuffix *regexp.Regexp
}{
	Full:             regexp.MustCompile(`(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?`),
	Minor:            regexp.MustCompile(`(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)`),
	Patch:            regexp.MustCompile(`(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)`),
	PreReleaseSuffix: regexp.MustCompile(`\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?`),
}

func validVersionFormat(version string, validation ...*regexp.Regexp) bool {
	var semverRegex *regexp.Regexp

	switch len(validation) {
	case 0:
		semverRegex = regexSemVer.Full
	case 1:
		semverRegex = validation[0]
	default:
		logger.Fatalf("Internal error: invalid number of arguments (must be 2, got %d)", 1+len(validation))
	}

	return semverRegex.MatchString(version)
}
```

File: lib/list_versions.go [hunk 4]
```diff
@@ -183,34 +190,35 @@ func removeDuplicateVersions(elements []string) []string {
...
 
-// ValidMinorVersionFormat : returns valid MINOR version format
-/* For example: 0.1 = valid
-// For example: a.1.2 = invalid
-// For example: 0.1.2 = invalid
-*/
-func validMinorVersionFormat(version string) bool {
-	// Getting versions from body; should return match /X.X./ where X is a number
-	semverRegex := regexp.MustCompile(`^(\d+\.\d+)$`)
+	switch verType {
```
Comment (MatthewJohn) [inline lib/list_versions.go]: As suggested, this seems quite overly verbose and relying on magic strings (and duplicates the names of the keys in the map).

Comment (yermulnik) [reply lib/list_versions.go]: Won't be able to get rid of magic strings at this moment as regexps are used with different anchors throughout this file. The rest of comments and ideas from the other thread are being worked on towards implementation.

File: lib/list_versions.go (hunk 3 above)
Comment (yermulnik) [reply lib/list_versions.go]: Appreciate this much useful feedback 👍🏻 Working on implementation.

Comment (yermulnik) [reply lib/list_versions.go]: Hopefully I did as much as I could: 5c4ca9d
Please review.

File: lib/param_parsing/parameters.go [hunk 5]
```diff
@@ -83,13 +83,13 @@ func populateParams(params Params) Params {
...
-	getopt.StringVarLong(&params.ShowLatestPre, "show-latest-pre", 'P', "Show latest pre-release implicit version. Ex: tfswitch --show-latest-pre 0.13 prints 0.13.0-rc1 (latest)")
-	getopt.StringVarLong(&params.ShowLatestStable, "show-latest-stable", 'S', "Show latest implicit version. Ex: tfswitch --show-latest-stable 0.13 prints 0.13.7 (latest)")
 	getopt.StringVarLong(&params.Product, "product", 't', fmt.Sprintf("Specifies which product to use. Ex: `tfswitch --product opentofu` will install OpenTofu. Options: (%s). Default: %s", strings.Join(productIds, ", "), lib.DefaultProductId))
+	getopt.StringVarLong(&params.ShowLatestPre, "show-latest-pre", 'P', "Show latest pre-release implicit version. Accepts #.# as argument where # are numbers. Ex: tfswitch --show-latest-pre 0.13 prints latest in 0.13.x branch up to pre-release (if any)")
+	getopt.StringVarLong(&params.ShowLatestStable, "show-latest-stable", 'S', "Show latest stable implicit version. Accepts either #.# or #.#.# as argument where # are numbers. Ex: tfswitch --show-latest-stable 0.13.0 prints latest in 0.13.x branch, 0.13 prints latest in 0.x branch, 1.1 prints latest in 1.x branch")
```
[the remark this answers is not in the document]
Comment (yermulnik) [reply lib/param_parsing/parameters.go:92]: irrelevant comment

File: lib/list_versions.go [hunk 6]
```diff
@@ -220,9 +230,9 @@ func ShowLatestVersion(mirrorURL string) {
 	fmt.Printf("%s\n", tfversion)
 }
 
-// ShowLatestImplicitVersion show latest - argument (version) must be provided
+// ShowLatestImplicitVersion : show latest implicit version given the mirror URL
 func ShowLatestImplicitVersion(requestedVersion, mirrorURL string, preRelease bool) {
-	if validMinorVersionFormat(requestedVersion) {
+	if validVersionFormat(requestedVersion, regexSemVer.Minor) || (validVersionFormat(requestedVersion, regexSemVer.Patch) && !preRelease) {
```
[the remark this answers is not in the document]
Comment (yermulnik) [reply lib/list_versions.go:233]: irrelevant

File: lib/list_versions_test.go [hunk 7]
```diff
@@ -165,11 +165,8 @@ func TestGetTFLatest(t *testing.T) {
 func TestGetTFLatestImplicit(t *testing.T) {
 	logger = InitLogger("DEBUG")
 	tName := "version=%s_preRelease=%v"
-	t.Run(fmt.Sprintf(tName, "0.11.0", false), func(t *testing.T) { testGetTFLatestImplicit(t, "0.11.0", false, "0.11.13") })
-	// @TODO Couldn't get this test working
-	// t.Run(fmt.Sprintf(tName, "0.11", true), func(t *testing.T) { testGetTFLatestImplicit(t, "0.11", true, "0.11.13") })
+	t.Run(fmt.Sprintf(tName, "0.11.0", false), func(t *testing.T) { testGetTFLatestImplicit(t, "0.12.0", false, "0.12.2") })
```
[the remark this answers is not in the document]
Comment (yermulnik) [reply lib/list_versions_test.go]: Thanks. Addressed: b4d8123

File: lib/list_versions.go [hunk 8]
```diff
@@ -183,34 +196,31 @@ func removeDuplicateVersions(elements []string) []string {
...
+	case 1:
+		semverRegex = validation[0]
+		// Limit the valid values in this switch case to only minor and patch versions,
+		// as currently it is used in `ShowLatestImplicitVersion()` only
+		validValues := []*regexp.Regexp{regexSemVer.Minor, regexSemVer.Patch}
+		if !slices.Contains(validValues, semverRegex) {
+			logger.Fatalf("Internal error: invalid \"validation\" argument value")
+		}
+	default:
+		logger.Fatalf("Internal error: invalid number of arguments (must be 2, got %d)", 1+len(validation))
```
[the remark this answers is not in the document]
Comment (yermulnik) [reply lib/list_versions.go]: Thanks. Addressed: 6a51376

File: lib/list_versions.go [hunk 9]
```diff
@@ -183,34 +196,31 @@ func removeDuplicateVersions(elements []string) []string {
...
-*/
-func validVersionFormat(version string) bool {
-	// Getting versions from body; should return match /X.X.X-@/ where X is a number,@ is a word character between a-z or A-Z
-	// Follow https://semver.org/spec/v1.0.0-beta.html
-	// Check regular expression at https://rubular.com/r/ju3PxbaSBALpJB
-	semverRegex := regexp.MustCompile(`^(\d+\.\d+\.\d+)(-[a-zA-z]+\d*)?$`)
-	return semverRegex.MatchString(version)
-}
+// validVersionFormat : Return true if valid semantic version provided based on the type of version requested
+func validVersionFormat(version string, validation ...*regexp.Regexp) bool {
```
Comment (MatthewJohn) [inline lib/list_versions.go:200]: I guess noting that if you _don't_ pass validation, it uses Full, but you can't pass full 🤔

File: lib/list_versions.go [hunk 10]
```diff
@@ -183,34 +196,31 @@ func removeDuplicateVersions(elements []string) []string {
...
 
-// ValidMinorVersionFormat : returns valid MINOR version format
-/* For example: 0.1 = valid
-// For example: a.1.2 = invalid
-// For example: 0.1.2 = invalid
-*/
-func validMinorVersionFormat(version string) bool {
-	// Getting versions from body; should return match /X.X./ where X is a number
-	semverRegex := regexp.MustCompile(`^(\d+\.\d+)$`)
+	semverRegex = regexp.MustCompile(`^` + semverRegex.String() + `$`)
```
Comment (MatthewJohn) [inline lib/list_versions.go:216]: It's a shame that the original versions can't include the match of start/end, and require Compile(Compile().String()), but oh well, I think it's definitely safer as is :)

File: lib/list_versions_test.go [hunk 11]
```diff
@@ -215,96 +213,117 @@ func TestRemoveDuplicateVersions(t *testing.T) {
...
-		t.Logf("Valid version format : %s (expected)", version)
+	if valid == false {
+		t.Logf("Invalid version format : %s (expected)", version)
 	} else {
 		t.Errorf("Failed to verify version format: %s\n", version)
 	}
 
-	version = "1.11.4-boom"
-
+	version = "1.11.4-01"
```
Comment (MatthewJohn) [inline lib/list_versions_test.go:319]: Why is : `version = "0.12.0-rc2"` valid, but this isn't? 🤔

File: lib/list_versions.go (hunk 10 above)
Comment (yermulnik) [reply lib/list_versions.go:216]: Yeah, that's a hiccup. We use those regexps to parse HTML body for valid versions from Mirror URL and those need to be not wrapped in `^` and `$` anchors. E.g. https://github.com/warrensbox/terraform-switcher/blob/issue-585/fix-show-and-install-latest-stable/lib/list_versions.go#L32-L39
```go

func getVersionsFromBody(body string, preRelease bool, tfVersionList *tfVersionList) {
        var semver string
        // Without the ending '"' pre-release folders would be tried and break.
        if preRelease {
                semver = `\/?` + regexSemVer.Full.String() + `/?"`
        } else if !preRelease {
                semver = `\/?` + regexSemVer.Patch.String() + `\/?"`
        }
```
So I'm leaving to a future re-factoring/improvement.

File: lib/list_versions_test.go (hunk 11 above)
Comment (yermulnik) [reply lib/list_versions_test.go:319]: https://semver.org/#spec-item-9 (see the text highlighted with bold font)
> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. **Numeric identifiers MUST NOT include leading zeroes**. […]

File: lib/list_versions.go (hunk 9 above)
Comment (yermulnik) [reply lib/list_versions.go:200]: Hmm... I was trying to make the check as specific as possible, but... but I guess you;re right that it's a bit of overengineering. I'm going to update it now to make it more general-purpose and less strict.

Comment (yermulnik) [reply lib/list_versions.go:200]: @MatthewJohn eb5e3f6

File: lib/semver.go [hunk 12]
```diff
@@ -58,7 +58,12 @@ func PrintInvalidTFVersion() {
 	logger.Error("Version does not exist or invalid terraform version format.\n\tFormat should be #.#.# or #.#.#-@# where # are numbers and @ are word characters.\n\tFor example, 1.11.7 and 0.11.9-beta1 are valid versions")
 }
 
-// PrintInvalidMinorTFVersion Print invalid minor TF version
+// PrintInvalidMinorTFVersion Print invalid minor version format
```
[the remark this answers is not in the document]
Comment (yermulnik) [reply lib/semver.go:61]: No trailing period is consistent with the current file's convention.

File: lib/semver.go [hunk 13]
```diff
@@ -58,7 +58,12 @@ func PrintInvalidTFVersion() {
...
 func PrintInvalidMinorTFVersion() {
 	logger.Error("Invalid minor terraform version format.\n\tFormat should be #.# where # are numbers. For example, 1.11 is valid version")
 }
+
+// printInvalidVersionFormat Print invalid version format
```
[the remark this answers is not in the document]
Comment (yermulnik) [reply lib/semver.go:66]: No trailing period is consistent with the current file's convention.

File: lib/list_versions.go [hunk 14]
```diff
@@ -14,15 +14,27 @@ type tfVersionList struct {
...
 
+// Semantic version regexes without `^` and `$` anchors
+// Follows https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
+var regexSemVer = struct {
+	Full             *regexp.Regexp
+	Minor            *regexp.Regexp
+	Patch            *regexp.Regexp
+	PreReleaseSuffix *regexp.Regexp
+}{
+	Full:             regexp.MustCompile(`(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?`),
```
[the remark this answers is not in the document]
Comment (yermulnik) [reply lib/list_versions.go:25]: An interesting suggestion... 🤔 Though at this stage I see no need for lazy init as I don't think their compilation at binary compilation time is anything expensive and hence it isn't worth of effort.

File: lib/list_versions.go [hunk 15]
```diff
@@ -183,34 +195,30 @@ func removeDuplicateVersions(elements []string) []string {
...
 
-// ValidMinorVersionFormat : returns valid MINOR version format
-/* For example: 0.1 = valid
-// For example: a.1.2 = invalid
-// For example: 0.1.2 = invalid
-*/
-func validMinorVersionFormat(version string) bool {
-	// Getting versions from body; should return match /X.X./ where X is a number
-	semverRegex := regexp.MustCompile(`^(\d+\.\d+)$`)
+	semverRegex = regexp.MustCompile(`^` + semverRegex.String() + `$`)
```
[the remark this answers is not in the document]
Comment (yermulnik) [reply lib/list_versions.go:217]: Yeah, we'll need to give this a thought and maybe re-factor later. Good job catching this bit 👍🏻 There's an response to the similar comment: https://github.com/warrensbox/terraform-switcher/pull/601#discussion_r2226071385

File: lib/list_versions.go (hunk 9 above)
Comment (MatthewJohn) [reply lib/list_versions.go:200]: I approved, was just a passing comment :)

**Review by MatthewJohn — APPROVED** [review]

File: lib/list_versions.go (hunk 9 above)
Comment (yermulnik) [reply lib/list_versions.go:200]: It was a good comment which was worth of rethinking this bit and I did it. Appreciate your worthwhile and helpful reviews 👍🏻
